# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-14.04"
  
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  
  
  config.vm.provision "file", source: "tapas", destination: "$HOME/tapas"
  config.vm.provision "file", source: "test-content", destination: "$HOME/test-content"
  config.vm.provision "file", source: "content", destination: "$HOME/content"
	config.vm.provision "file", source: "bash", destination: "$HOME"
  config.vm.provision :shell, path: "provision.sh"

 
end
